apiVersion: v1
kind: Pod
metadata:
  name: transfer-pod
spec:
  containers:
  - name: gpu-container
    image: gitlab-registry.nautilus.optiputer.net/prp/jupyterlab:latest
    command: ["sleep", "infinity"]
    resources:
      limits:
        nvidia.com/gpu: 1
    volumeMounts:
    - mountPath: /racelab
      name: fs-store
  volumes:
    - name: fs-store
      flexVolume:
        driver: ceph.rook.io/rook
        fsType: ceph
        options:
          clusterNamespace: rook
          fsName: nautilusfs
          path: /racelab
          mountUser: racelab
          mountSecret: ceph-fs-secret
  